include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/localization/src/generated/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - literal_only_boolean_expressions
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_implementing_value_types
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - cast_nullable_to_non_nullable
    - conditional_uri_does_not_exist
    - directives_ordering
    - eol_at_end_of_file
    - join_return_with_assignment
    - noop_primitive_operations
    - omit_local_variable_types
    - one_member_abstracts
    - prefer_asserts_in_initializer_lists
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - sized_box_shrink_expand
    - tighten_type_of_initializing_formals
    - unnecessary_await_in_return
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_to_list_in_spreads
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_string_buffers
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
