name: location_api
description: A client providing access to the location service.
version: 0.0.1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  geolocator: ^9.0.1

dev_dependencies:
  test: ^1.21.4