name: weather_api
description: A client providing access to WeatherApi.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.21.4
