name: Code style and tests

on:
  push:
    branches: 
      - main
    
permissions:
  contents: read

jobs:
  style-and-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download the commit to a runner
        uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check the commit is formatted well 
        run: dart format --line-length=80 --output=none --set-exit-if-changed .
      
      - name: Check the commit passes Dart Analyzer
        run: flutter analyze --fatal-warnings --fatal-infos
      
      - name: Run tests
        run: flutter test --no-pub --reporter=github
